### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by bizouarn** [Hedroed/PlanningIUT#1]
@Hedroed Bonjour, je travaille actuellement sur une nouvelle version de PlaningIUT. Pour le remettre au gout du jour et éviter les crash serveur. Mais j'aimerai savoir comment tu as fait pour récupérer les adresses des plannings.

**Comment by Hedroed** [comment]
Salut,
C'est génial que tu reprends PlanningIUT, je préférerais te répondre par mail si ca ne te dérange pas.
Contacte moi par mail à nathan.rydin@gmail.com.
